/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewRouteImport } from './routes/view'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelectRouteImport } from './routes/select'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ApiSubjectsRouteImport } from './routes/api/subjects'
import { Route as ApiResourcesRouteImport } from './routes/api/resources'
import { Route as ApiCreateOrderRouteImport } from './routes/api/create-order'
import { Route as ApiAdminUploadSubjectRouteImport } from './routes/api/admin/upload-subject'
import { Route as ApiAdminUploadResourceRouteImport } from './routes/api/admin/upload-resource'
import { Route as ApiAdminUpdateSubjectRouteImport } from './routes/api/admin/update-subject'
import { Route as ApiAdminUpdateResourceRouteImport } from './routes/api/admin/update-resource'
import { Route as ApiAdminSubjectsRouteImport } from './routes/api/admin/subjects'
import { Route as ApiAdminResourcesRouteImport } from './routes/api/admin/resources'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminDeleteSubjectRouteImport } from './routes/api/admin/delete-subject'
import { Route as ApiAdminDeleteResourceRouteImport } from './routes/api/admin/delete-resource'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminBulkResourceUpdateRouteImport } from './routes/api/admin/bulk-resource-update'
import { Route as ApiAdminBulkPriceUpdateRouteImport } from './routes/api/admin/bulk-price-update'
import { Route as ApiResourceDownloadSlugRouteImport } from './routes/api/resource/download/$slug'

const ViewRoute = ViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubjectsRoute = ApiSubjectsRouteImport.update({
  id: '/api/subjects',
  path: '/api/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesRoute = ApiResourcesRouteImport.update({
  id: '/api/resources',
  path: '/api/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadSubjectRoute = ApiAdminUploadSubjectRouteImport.update({
  id: '/api/admin/upload-subject',
  path: '/api/admin/upload-subject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadResourceRoute = ApiAdminUploadResourceRouteImport.update({
  id: '/api/admin/upload-resource',
  path: '/api/admin/upload-resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateSubjectRoute = ApiAdminUpdateSubjectRouteImport.update({
  id: '/api/admin/update-subject',
  path: '/api/admin/update-subject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateResourceRoute = ApiAdminUpdateResourceRouteImport.update({
  id: '/api/admin/update-resource',
  path: '/api/admin/update-resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubjectsRoute = ApiAdminSubjectsRouteImport.update({
  id: '/api/admin/subjects',
  path: '/api/admin/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResourcesRoute = ApiAdminResourcesRouteImport.update({
  id: '/api/admin/resources',
  path: '/api/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteSubjectRoute = ApiAdminDeleteSubjectRouteImport.update({
  id: '/api/admin/delete-subject',
  path: '/api/admin/delete-subject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteResourceRoute = ApiAdminDeleteResourceRouteImport.update({
  id: '/api/admin/delete-resource',
  path: '/api/admin/delete-resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBulkResourceUpdateRoute =
  ApiAdminBulkResourceUpdateRouteImport.update({
    id: '/api/admin/bulk-resource-update',
    path: '/api/admin/bulk-resource-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminBulkPriceUpdateRoute = ApiAdminBulkPriceUpdateRouteImport.update({
  id: '/api/admin/bulk-price-update',
  path: '/api/admin/bulk-price-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourceDownloadSlugRoute = ApiResourceDownloadSlugRouteImport.update({
  id: '/api/resource/download/$slug',
  path: '/api/resource/download/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/privacy': typeof PrivacyRoute
  '/purchase': typeof PurchaseRoute
  '/resources': typeof ResourcesRoute
  '/select': typeof SelectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/view': typeof ViewRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/subjects': typeof ApiSubjectsRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/admin/bulk-price-update': typeof ApiAdminBulkPriceUpdateRoute
  '/api/admin/bulk-resource-update': typeof ApiAdminBulkResourceUpdateRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/delete-resource': typeof ApiAdminDeleteResourceRoute
  '/api/admin/delete-subject': typeof ApiAdminDeleteSubjectRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/subjects': typeof ApiAdminSubjectsRoute
  '/api/admin/update-resource': typeof ApiAdminUpdateResourceRoute
  '/api/admin/update-subject': typeof ApiAdminUpdateSubjectRoute
  '/api/admin/upload-resource': typeof ApiAdminUploadResourceRoute
  '/api/admin/upload-subject': typeof ApiAdminUploadSubjectRoute
  '/api/resource/download/$slug': typeof ApiResourceDownloadSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/privacy': typeof PrivacyRoute
  '/purchase': typeof PurchaseRoute
  '/resources': typeof ResourcesRoute
  '/select': typeof SelectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/view': typeof ViewRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/subjects': typeof ApiSubjectsRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/admin/bulk-price-update': typeof ApiAdminBulkPriceUpdateRoute
  '/api/admin/bulk-resource-update': typeof ApiAdminBulkResourceUpdateRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/delete-resource': typeof ApiAdminDeleteResourceRoute
  '/api/admin/delete-subject': typeof ApiAdminDeleteSubjectRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/subjects': typeof ApiAdminSubjectsRoute
  '/api/admin/update-resource': typeof ApiAdminUpdateResourceRoute
  '/api/admin/update-subject': typeof ApiAdminUpdateSubjectRoute
  '/api/admin/upload-resource': typeof ApiAdminUploadResourceRoute
  '/api/admin/upload-subject': typeof ApiAdminUploadSubjectRoute
  '/api/resource/download/$slug': typeof ApiResourceDownloadSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/privacy': typeof PrivacyRoute
  '/purchase': typeof PurchaseRoute
  '/resources': typeof ResourcesRoute
  '/select': typeof SelectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/view': typeof ViewRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/subjects': typeof ApiSubjectsRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/admin/bulk-price-update': typeof ApiAdminBulkPriceUpdateRoute
  '/api/admin/bulk-resource-update': typeof ApiAdminBulkResourceUpdateRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/delete-resource': typeof ApiAdminDeleteResourceRoute
  '/api/admin/delete-subject': typeof ApiAdminDeleteSubjectRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/subjects': typeof ApiAdminSubjectsRoute
  '/api/admin/update-resource': typeof ApiAdminUpdateResourceRoute
  '/api/admin/update-subject': typeof ApiAdminUpdateSubjectRoute
  '/api/admin/upload-resource': typeof ApiAdminUploadResourceRoute
  '/api/admin/upload-subject': typeof ApiAdminUploadSubjectRoute
  '/api/resource/download/$slug': typeof ApiResourceDownloadSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/privacy'
    | '/purchase'
    | '/resources'
    | '/select'
    | '/sitemap.xml'
    | '/view'
    | '/api/create-order'
    | '/api/resources'
    | '/api/subjects'
    | '/api/verify-payment'
    | '/api/admin/bulk-price-update'
    | '/api/admin/bulk-resource-update'
    | '/api/admin/dashboard'
    | '/api/admin/delete-resource'
    | '/api/admin/delete-subject'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/resources'
    | '/api/admin/subjects'
    | '/api/admin/update-resource'
    | '/api/admin/update-subject'
    | '/api/admin/upload-resource'
    | '/api/admin/upload-subject'
    | '/api/resource/download/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/privacy'
    | '/purchase'
    | '/resources'
    | '/select'
    | '/sitemap.xml'
    | '/view'
    | '/api/create-order'
    | '/api/resources'
    | '/api/subjects'
    | '/api/verify-payment'
    | '/api/admin/bulk-price-update'
    | '/api/admin/bulk-resource-update'
    | '/api/admin/dashboard'
    | '/api/admin/delete-resource'
    | '/api/admin/delete-subject'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/resources'
    | '/api/admin/subjects'
    | '/api/admin/update-resource'
    | '/api/admin/update-subject'
    | '/api/admin/upload-resource'
    | '/api/admin/upload-subject'
    | '/api/resource/download/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/privacy'
    | '/purchase'
    | '/resources'
    | '/select'
    | '/sitemap.xml'
    | '/view'
    | '/api/create-order'
    | '/api/resources'
    | '/api/subjects'
    | '/api/verify-payment'
    | '/api/admin/bulk-price-update'
    | '/api/admin/bulk-resource-update'
    | '/api/admin/dashboard'
    | '/api/admin/delete-resource'
    | '/api/admin/delete-subject'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/resources'
    | '/api/admin/subjects'
    | '/api/admin/update-resource'
    | '/api/admin/update-subject'
    | '/api/admin/upload-resource'
    | '/api/admin/upload-subject'
    | '/api/resource/download/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  PurchaseRoute: typeof PurchaseRoute
  ResourcesRoute: typeof ResourcesRoute
  SelectRoute: typeof SelectRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ViewRoute: typeof ViewRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiResourcesRoute: typeof ApiResourcesRoute
  ApiSubjectsRoute: typeof ApiSubjectsRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  ApiAdminBulkPriceUpdateRoute: typeof ApiAdminBulkPriceUpdateRoute
  ApiAdminBulkResourceUpdateRoute: typeof ApiAdminBulkResourceUpdateRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminDeleteResourceRoute: typeof ApiAdminDeleteResourceRoute
  ApiAdminDeleteSubjectRoute: typeof ApiAdminDeleteSubjectRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminResourcesRoute: typeof ApiAdminResourcesRoute
  ApiAdminSubjectsRoute: typeof ApiAdminSubjectsRoute
  ApiAdminUpdateResourceRoute: typeof ApiAdminUpdateResourceRoute
  ApiAdminUpdateSubjectRoute: typeof ApiAdminUpdateSubjectRoute
  ApiAdminUploadResourceRoute: typeof ApiAdminUploadResourceRoute
  ApiAdminUploadSubjectRoute: typeof ApiAdminUploadSubjectRoute
  ApiResourceDownloadSlugRoute: typeof ApiResourceDownloadSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subjects': {
      id: '/api/subjects'
      path: '/api/subjects'
      fullPath: '/api/subjects'
      preLoaderRoute: typeof ApiSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources': {
      id: '/api/resources'
      path: '/api/resources'
      fullPath: '/api/resources'
      preLoaderRoute: typeof ApiResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-subject': {
      id: '/api/admin/upload-subject'
      path: '/api/admin/upload-subject'
      fullPath: '/api/admin/upload-subject'
      preLoaderRoute: typeof ApiAdminUploadSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-resource': {
      id: '/api/admin/upload-resource'
      path: '/api/admin/upload-resource'
      fullPath: '/api/admin/upload-resource'
      preLoaderRoute: typeof ApiAdminUploadResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-subject': {
      id: '/api/admin/update-subject'
      path: '/api/admin/update-subject'
      fullPath: '/api/admin/update-subject'
      preLoaderRoute: typeof ApiAdminUpdateSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-resource': {
      id: '/api/admin/update-resource'
      path: '/api/admin/update-resource'
      fullPath: '/api/admin/update-resource'
      preLoaderRoute: typeof ApiAdminUpdateResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subjects': {
      id: '/api/admin/subjects'
      path: '/api/admin/subjects'
      fullPath: '/api/admin/subjects'
      preLoaderRoute: typeof ApiAdminSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/resources': {
      id: '/api/admin/resources'
      path: '/api/admin/resources'
      fullPath: '/api/admin/resources'
      preLoaderRoute: typeof ApiAdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-subject': {
      id: '/api/admin/delete-subject'
      path: '/api/admin/delete-subject'
      fullPath: '/api/admin/delete-subject'
      preLoaderRoute: typeof ApiAdminDeleteSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-resource': {
      id: '/api/admin/delete-resource'
      path: '/api/admin/delete-resource'
      fullPath: '/api/admin/delete-resource'
      preLoaderRoute: typeof ApiAdminDeleteResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bulk-resource-update': {
      id: '/api/admin/bulk-resource-update'
      path: '/api/admin/bulk-resource-update'
      fullPath: '/api/admin/bulk-resource-update'
      preLoaderRoute: typeof ApiAdminBulkResourceUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bulk-price-update': {
      id: '/api/admin/bulk-price-update'
      path: '/api/admin/bulk-price-update'
      fullPath: '/api/admin/bulk-price-update'
      preLoaderRoute: typeof ApiAdminBulkPriceUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resource/download/$slug': {
      id: '/api/resource/download/$slug'
      path: '/api/resource/download/$slug'
      fullPath: '/api/resource/download/$slug'
      preLoaderRoute: typeof ApiResourceDownloadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  PrivacyRoute: PrivacyRoute,
  PurchaseRoute: PurchaseRoute,
  ResourcesRoute: ResourcesRoute,
  SelectRoute: SelectRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ViewRoute: ViewRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiResourcesRoute: ApiResourcesRoute,
  ApiSubjectsRoute: ApiSubjectsRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  ApiAdminBulkPriceUpdateRoute: ApiAdminBulkPriceUpdateRoute,
  ApiAdminBulkResourceUpdateRoute: ApiAdminBulkResourceUpdateRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminDeleteResourceRoute: ApiAdminDeleteResourceRoute,
  ApiAdminDeleteSubjectRoute: ApiAdminDeleteSubjectRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminResourcesRoute: ApiAdminResourcesRoute,
  ApiAdminSubjectsRoute: ApiAdminSubjectsRoute,
  ApiAdminUpdateResourceRoute: ApiAdminUpdateResourceRoute,
  ApiAdminUpdateSubjectRoute: ApiAdminUpdateSubjectRoute,
  ApiAdminUploadResourceRoute: ApiAdminUploadResourceRoute,
  ApiAdminUploadSubjectRoute: ApiAdminUploadSubjectRoute,
  ApiResourceDownloadSlugRoute: ApiResourceDownloadSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
